## Learn about numpy 

In [4]:
import numpy as np

 ### Creating array from list 

In [ ]:
np_array1 = np.array([1,2,3])
print("The array 1 is :",np_array1)

np_array2 = np.array([[1,2,3],[5,6,7]])
print("The array 2 is :",np_array2)

The array 1 is : [1 2 3]
The array 2 is : [[1 2 3]
 [5 6 7]]


### Array vs List


In [ ]:
py_list = [1,2,3]
print("Python list multiplication :", py_list *2)

np_array = np.array([1,2,3])  # element wise multiplication
print("Python array multiplication :", np_array *2)

import time 

start_time = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time : ",time.time()-start_time)

start_time = time.time()
np_array = np.arange(100000) * 2
print("\n Array operation time : ",time.time()-start_time)



Python list multiplication : [1, 2, 3, 1, 2, 3]
Python array multiplication : [2 4 6]

 List operation time :  0.0642538070678711

 Array operation time :  0.0005464553833007812


### Creating array from scratch 

In [ ]:
zero = np.zeros((3,4))
print("Zeros array : \n",zero)

ones = np.ones((2,3))
print("ones array : \n",ones)

full = np.full((2,2),7)    # ((para1,para2),number to print in array)
print("Full array : \n",full)

random = np.random.random((4,3))  # ((para1,para2))
print("Random array : \n",random)

sequence = np.arange(0,10,2)    #(start,stop,step)
print("Sequence array : ",sequence)



Zeros array : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array : 
 [[1. 1. 1.]
 [1. 1. 1.]]
Full array : 
 [[7 7]
 [7 7]]
Random array : 
 [[0.55651556 0.8507987  0.06551718]
 [0.15148702 0.46358498 0.57092777]
 [0.80311844 0.83965545 0.82601701]
 [0.6414975  0.32661707 0.5348122 ]]
Sequence array :  [0 2 4 6 8]


### Array Properties 

In [22]:
arr = np.array([[1,2,3],[4,5,6]])

print ("Shape :" ,arr.shape)
print ("Dimension : ",arr.ndim)
print ("Size : ",arr.size)
print ("Datatype : ",arr.dtype)


Shape : (2, 3)
Dimension :  2
Size :  6
Datatype :  int64


### Array Reshaping 

In [21]:
arr = np.arange(12)
print("Original array :",arr)

reshaped = arr.reshape((3,4))
print("Reshaped array : \n ",reshaped)

flattened = reshaped.flatten()
print("Flatened array : ",flattened)

# raveled returns the view(original) not the copy 
raveled = reshaped.ravel()
print("Raveled array : ",raveled)

#Transpose 
transpose = reshaped.T
print("Tranpose array : \n", transpose)








Original array : [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array : 
  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flatened array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Tranpose array : 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
